import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navbar}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
          <li>Contect</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcom to Hunting Coder</h1>

        <p className={styles.description}>A blog for hunting coders</p>

        <div className="blog">
          <h2>Popular Blogs</h2>

          <div className="blog-post">
            <h3>How to learn NextJs in 3rd Year</h3>
            <p>It is quite easy to learn Next but it requies patience</p>
          </div>
          <div className="blog-post">
            <h3>How to learn NextJs in 3rd Year</h3>
            <p>It is quite easy to learn Next but it requies patience</p>
          </div>
          <div className="blog-post">
            <h3>How to learn NextJs in 3rd Year</h3>
            <p>It is quite easy to learn Next but it requies patience</p>
          </div>
          <div className="blog-post">
            <h3>How to learn NextJs in 3rd Year</h3>
            <p>It is quite easy to learn Next but it requies patience</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
